version: '3.9'

services:
  redis-stack-2:
    image: redis/redis-stack:latest
    container_name: litellm-redis
    environment:
      - REDIS_ARGS=--requirepass budpassword
    ports:
      - "6342:6379"
      - "8005:8001"
    restart: always
