apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-subscription
spec:
  topic: budLitellmMessages
  routes:
    default: /notifications
  pubsubname: pubsub-redis
  deadLetterTopic: poisonMessages
scopes:
  - budlitellm